### ISSUE TITLE
genpasswd() doesn't work in the REPL

### ISSUE THREAD

**Issue by ProgrammAbel** [ProgrammAbel/PassMan#1]
What the title says. It spits out
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abelb/Projects/PassMan/main.py", line 9, in genpasswd
    hash = hashlib.sha256(salted).digest()
TypeError: Unicode-objects must be encoded before hashing`

**Comment by ProgrammAbel** [comment]
The issue has been fixed.
