### ISSUE TITLE
'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by ProgrammAbel** [ProgrammAbel/PassMan#2]
When running from command-line, I get this:
`Traceback (most recent call last):
  File "./passman.py", line 46, in <module>
    main()
  File "./passman.py", line 42, in main
    genpasswd(website, masterpass)
  File "./passman.py", line 24, in genpasswd
    website = website.encode()
AttributeError: 'bytes' object has no attribute 'encode'`

**Comment by ProgrammAbel** [comment]
The issue has been fixed.
